name: Run on PyPy

on:
  push:
    branches: [ master, investigate-windows-failure ]
  pull_request:
    branches: [ master ]

jobs:
  test-all:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        python-version: [pypy3.8, pypy3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 'stable'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel
          python -m pip install .
          python -m pip install -r requirements_dev.txt

      - name: Test
        run: pytest --cov=. -s tests
        env:
          NIMPORTER_INSTRUMENT: 1
